Add bookingArrangements to Leg
entur/sdk pull request #207
Opened 2021-02-22 15:11 UTC by jarlestavne

And deprecate elsewhere.

2021-02-22 15:20 UTC, draperunner commented on src/fields/EstimatedCall.ts
> +    bookingArrangements?: BookingArrangement // @deprecated
Eg trur du må bruke denne syntaksen for at TypeScript skal registrere det riktig som TSDoc:
```
/** @deprecated Use bookingArrangements on Leg instead. */
bookingArrangements?: BookingArrangement 
```

Også lurt å legge på beskrivelse for å hjelpe brukarane på veg.

2021-02-22 15:20 UTC, draperunner commented on src/fields/ServiceJourney.ts
> +    bookingArrangements?: BookingArrangement // @deprecated
Både Line og ServiceJourney blir vel kanskje brukt i andre metodar der Leg og TripPattern ikkje er involvert. Kanskje me ikkje kan fjerne det frå desse? Då må ev. Leg bruke andre Line- og ServiceJourney-queries

2021-02-23 09:01 UTC, draperunner requested changes

2021-02-23 09:01 UTC, draperunner commented on src/fields/Line.ts
> +    /** @deprecated Use bookingArrangements on Leg instead. */
Du må nok fjerne deprecation her. Departures-metodane brukar ServiceJourney, som igjen spør om lines (og dermed bookingArrangements). I desse tilfella er det ingen Leg å bruke i staden.

2021-02-23 09:10 UTC, jarlestavne commented on src/fields/Line.ts
> +    /** @deprecated Use bookingArrangements on Leg instead. */
Men bookingArrangements ligger direkte på serviceJourney, så dette burde vel ikke være et problem?

2021-02-23 09:30 UTC, draperunner commented on src/fields/Line.ts
> +    /** @deprecated Use bookingArrangements on Leg instead. */
Åja, då er det vel greit. Me har visst bookingArrangements overalt. :)

2021-02-23 09:30 UTC, draperunner approved these changes

2021-02-23 14:34 UTC, closed without merging